/* The answers.
 *
 * Hand-written on purpose. Wikipedia and Wikidata will give you a photo and a
 * taxon, but they will not reliably tell you whether something is dangerous,
 * nocturnal, or kept as a pet - those are judgement calls, not structured
 * facts. Since the whole point is a fast, confident answer mid-argument, they
 * are written out rather than derived.
 *
 * Keys, kept short so one animal fits on a few readable lines:
 *   n  name              a   also known as (searchable)
 *   w  wikipedia title   e   emoji
 *   c  class             d   diet
 *   r  regions           dg  danger to humans: no | some | yes
 *   ac active: day | night | both        h   hibernates
 *   p  kept as a pet: no | some | common dm  domesticated
 *   et eaten by people: no | some | yes  cv  body covering
 *   co colours           sz  size: tiny | small | medium | large | huge
 *   lg legs              fl  can fly     sw  can swim
 *   eg lays eggs         so  social      lf  lifespan
 *   f  one good fact
 *
 * `w` defaults to the name when omitted.
 */

const ANIMALS = [
{n:"Lion",e:"🦁",c:"Mammal",d:"Carnivore",r:["Africa"],dg:"yes",ac:"night",h:false,p:"no",dm:false,et:"no",cv:"Fur",co:["tawny","gold"],sz:"large",lg:4,fl:false,sw:true,eg:false,so:"Prides",lf:"10–14 years",f:"The only truly social cat — everything else hunts alone."},
{n:"Tiger",e:"🐯",c:"Mammal",d:"Carnivore",r:["Asia"],dg:"yes",ac:"night",h:false,p:"no",dm:false,et:"no",cv:"Fur",co:["orange","black","white"],sz:"large",lg:4,fl:false,sw:true,eg:false,so:"Solitary",lf:"10–15 years",f:"Their skin is striped too, not just the fur."},
{n:"Leopard",e:"🐆",c:"Mammal",d:"Carnivore",r:["Africa","Asia"],dg:"yes",ac:"night",h:false,p:"no",dm:false,et:"no",cv:"Fur",co:["gold","black"],sz:"large",lg:4,fl:false,sw:true,eg:false,so:"Solitary",lf:"12–17 years",f:"Hauls kills heavier than itself up into trees."},
{n:"Cheetah",e:"🐆",c:"Mammal",d:"Carnivore",r:["Africa"],dg:"some",ac:"day",h:false,p:"no",dm:false,et:"no",cv:"Fur",co:["gold","black"],sz:"large",lg:4,fl:false,sw:false,eg:false,so:"Solitary",lf:"10–12 years",f:"The only big cat that cannot roar — it chirps."},
{n:"Jaguar",e:"🐆",c:"Mammal",d:"Carnivore",r:["South America","Central America"],dg:"yes",ac:"both",h:false,p:"no",dm:false,et:"no",cv:"Fur",co:["gold","black"],sz:"large",lg:4,fl:false,sw:true,eg:false,so:"Solitary",lf:"12–15 years",f:"Bites straight through the skull rather than the throat."},
{n:"Cougar",a:["puma","mountain lion","panther"],e:"🐈",c:"Mammal",d:"Carnivore",r:["North America","South America"],dg:"some",ac:"night",h:false,p:"no",dm:false,et:"no",cv:"Fur",co:["tan"],sz:"large",lg:4,fl:false,sw:true,eg:false,so:"Solitary",lf:"8–13 years",f:"Holds the record for most names of any animal in English."},
{n:"Domestic cat",a:["cat","kitty","moggy"],w:"Cat",e:"🐱",c:"Mammal",d:"Carnivore",r:["Worldwide"],dg:"no",ac:"night",h:false,p:"common",dm:true,et:"no",cv:"Fur",co:["black","white","ginger","grey","tabby"],sz:"small",lg:4,fl:false,sw:true,eg:false,so:"Solitary",lf:"12–18 years",f:"Purring sits in a frequency range linked to healing bone."},
{n:"Dog",a:["puppy","doggy"],e:"🐶",c:"Mammal",d:"Omnivore",r:["Worldwide"],dg:"some",ac:"day",h:false,p:"common",dm:true,et:"some",cv:"Fur",co:["black","white","brown","gold"],sz:"medium",lg:4,fl:false,sw:true,eg:false,so:"Packs",lf:"10–13 years",f:"The first animal we domesticated, well before farming."},
{n:"Wolf",e:"🐺",c:"Mammal",d:"Carnivore",r:["North America","Europe","Asia"],dg:"some",ac:"night",h:false,p:"no",dm:false,et:"no",cv:"Fur",co:["grey","white","black"],sz:"large",lg:4,fl:false,sw:true,eg:false,so:"Packs",lf:"6–8 years",f:"Every dog alive is descended from them."},
{n:"Red fox",a:["fox"],e:"🦊",c:"Mammal",d:"Omnivore",r:["Europe","North America","Asia"],dg:"no",ac:"night",h:false,p:"no",dm:false,et:"no",cv:"Fur",co:["orange","white"],sz:"medium",lg:4,fl:false,sw:true,eg:false,so:"Solitary",lf:"3–5 years",f:"Hunts using the Earth's magnetic field to aim its pounce."},
{n:"Brown bear",a:["grizzly","bear"],e:"🐻",c:"Mammal",d:"Omnivore",r:["North America","Europe","Asia"],dg:"yes",ac:"both",h:true,p:"no",dm:false,et:"some",cv:"Fur",co:["brown"],sz:"huge",lg:4,fl:false,sw:true,eg:false,so:"Solitary",lf:"20–25 years",f:"Does not truly hibernate — it dozes and can wake up."},
{n:"Polar bear",e:"🐻‍❄️",c:"Mammal",d:"Carnivore",r:["Arctic"],dg:"yes",ac:"both",h:false,p:"no",dm:false,et:"no",cv:"Fur",co:["white"],sz:"huge",lg:4,fl:false,sw:true,eg:false,so:"Solitary",lf:"20–25 years",f:"Its fur is see-through and its skin underneath is black."},
{n:"Panda",a:["giant panda"],w:"Giant_panda",e:"🐼",c:"Mammal",d:"Herbivore",r:["Asia"],dg:"some",ac:"both",h:false,p:"no",dm:false,et:"no",cv:"Fur",co:["black","white"],sz:"large",lg:4,fl:false,sw:true,eg:false,so:"Solitary",lf:"20 years",f:"A carnivore's gut that eats bamboo for 14 hours a day."},
{n:"Elephant",a:["african elephant"],w:"Elephant",e:"🐘",c:"Mammal",d:"Herbivore",r:["Africa","Asia"],dg:"yes",ac:"both",h:false,p:"no",dm:false,et:"no",cv:"Skin",co:["grey"],sz:"huge",lg:4,fl:false,sw:true,eg:false,so:"Herds",lf:"60–70 years",f:"Can hear one another through the ground, kilometres away."},
{n:"Giraffe",e:"🦒",c:"Mammal",d:"Herbivore",r:["Africa"],dg:"some",ac:"day",h:false,p:"no",dm:false,et:"no",cv:"Fur",co:["gold","brown"],sz:"huge",lg:4,fl:false,sw:false,eg:false,so:"Herds",lf:"25 years",f:"Same number of neck bones as you — seven."},
{n:"Zebra",e:"🦓",c:"Mammal",d:"Herbivore",r:["Africa"],dg:"some",ac:"day",h:false,p:"no",dm:false,et:"no",cv:"Fur",co:["black","white"],sz:"large",lg:4,fl:false,sw:true,eg:false,so:"Herds",lf:"25 years",f:"Never properly domesticated — they panic and they bite."},
{n:"Hippopotamus",a:["hippo"],e:"🦛",c:"Mammal",d:"Herbivore",r:["Africa"],dg:"yes",ac:"night",h:false,p:"no",dm:false,et:"no",cv:"Skin",co:["grey","pink"],sz:"huge",lg:4,fl:false,sw:true,eg:false,so:"Groups",lf:"40–50 years",f:"Kills more people a year than lions, leopards and crocodiles."},
{n:"Rhinoceros",a:["rhino"],e:"🦏",c:"Mammal",d:"Herbivore",r:["Africa","Asia"],dg:"yes",ac:"both",h:false,p:"no",dm:false,et:"no",cv:"Skin",co:["grey"],sz:"huge",lg:4,fl:false,sw:true,eg:false,so:"Solitary",lf:"35–50 years",f:"The horn is keratin — the same stuff as your fingernails."},
{n:"Gorilla",e:"🦍",c:"Mammal",d:"Herbivore",r:["Africa"],dg:"some",ac:"day",h:false,p:"no",dm:false,et:"no",cv:"Fur",co:["black","silver"],sz:"large",lg:2,fl:false,sw:false,eg:false,so:"Troops",lf:"35–40 years",f:"Builds a fresh nest to sleep in every single night."},
{n:"Chimpanzee",a:["chimp"],e:"🐒",c:"Mammal",d:"Omnivore",r:["Africa"],dg:"some",ac:"day",h:false,p:"no",dm:false,et:"no",cv:"Fur",co:["black"],sz:"medium",lg:2,fl:false,sw:false,eg:false,so:"Troops",lf:"40 years",f:"Makes and carries its own tools, and teaches them to others."},
{n:"Orangutan",e:"🦧",c:"Mammal",d:"Omnivore",r:["Asia"],dg:"some",ac:"day",h:false,p:"no",dm:false,et:"no",cv:"Fur",co:["orange"],sz:"large",lg:2,fl:false,sw:false,eg:false,so:"Solitary",lf:"35–45 years",f:"The name means 'person of the forest' in Malay."},
{n:"Monkey",a:["macaque"],e:"🐵",c:"Mammal",d:"Omnivore",r:["Africa","Asia","South America"],dg:"some",ac:"day",h:false,p:"no",dm:false,et:"some",cv:"Fur",co:["brown","grey"],sz:"small",lg:4,fl:false,sw:true,eg:false,so:"Troops",lf:"15–25 years",f:"If it has a tail it is a monkey; apes do not have one."},
{n:"Sloth",e:"🦥",c:"Mammal",d:"Herbivore",r:["South America","Central America"],dg:"no",ac:"both",h:false,p:"no",dm:false,et:"some",cv:"Fur",co:["brown","green"],sz:"medium",lg:4,fl:false,sw:true,eg:false,so:"Solitary",lf:"20–30 years",f:"Algae grows in its fur, which is why it looks faintly green."},
{n:"Koala",e:"🐨",c:"Mammal",d:"Herbivore",r:["Australia"],dg:"no",ac:"night",h:false,p:"no",dm:false,et:"no",cv:"Fur",co:["grey"],sz:"small",lg:4,fl:false,sw:true,eg:false,so:"Solitary",lf:"13–18 years",f:"Sleeps 20 hours a day because eucalyptus is barely food."},
{n:"Kangaroo",e:"🦘",c:"Mammal",d:"Herbivore",r:["Australia"],dg:"some",ac:"night",h:false,p:"no",dm:false,et:"yes",cv:"Fur",co:["brown","grey","red"],sz:"large",lg:2,fl:false,sw:true,eg:false,so:"Mobs",lf:"8–12 years",f:"Physically cannot walk backwards."},
{n:"Platypus",e:"🦆",c:"Mammal",d:"Carnivore",r:["Australia"],dg:"some",ac:"night",h:false,p:"no",dm:false,et:"no",cv:"Fur",co:["brown"],sz:"small",lg:4,fl:false,sw:true,eg:true,so:"Solitary",lf:"12–17 years",f:"A mammal that lays eggs, and the males have venomous spurs."},
{n:"Wombat",e:"🐨",c:"Mammal",d:"Herbivore",r:["Australia"],dg:"no",ac:"night",h:false,p:"no",dm:false,et:"some",cv:"Fur",co:["brown","grey"],sz:"medium",lg:4,fl:false,sw:true,eg:false,so:"Solitary",lf:"15 years",f:"Produces cube-shaped droppings. Genuinely."},
{n:"Hedgehog",e:"🦔",c:"Mammal",d:"Insectivore",r:["Europe","Asia","Africa"],dg:"no",ac:"night",h:true,p:"some",dm:false,et:"some",cv:"Spines",co:["brown"],sz:"small",lg:4,fl:false,sw:true,eg:false,so:"Solitary",lf:"3–7 years",f:"Immune to quite a lot of snake venom."},
{n:"Squirrel",e:"🐿️",c:"Mammal",d:"Omnivore",r:["Worldwide"],dg:"no",ac:"day",h:false,p:"no",dm:false,et:"some",cv:"Fur",co:["grey","red","brown"],sz:"small",lg:4,fl:false,sw:true,eg:false,so:"Solitary",lf:"5–10 years",f:"Forgets where it buried things, and accidentally plants forests."},
{n:"Rabbit",a:["bunny"],e:"🐰",c:"Mammal",d:"Herbivore",r:["Worldwide"],dg:"no",ac:"both",h:false,p:"common",dm:true,et:"yes",cv:"Fur",co:["brown","white","grey","black"],sz:"small",lg:4,fl:false,sw:true,eg:false,so:"Groups",lf:"8–12 years",f:"Its teeth never stop growing, all its life."},
{n:"Hare",e:"🐇",c:"Mammal",d:"Herbivore",r:["Europe","Asia","North America","Africa"],dg:"no",ac:"night",h:false,p:"no",dm:false,et:"yes",cv:"Fur",co:["brown"],sz:"small",lg:4,fl:false,sw:true,eg:false,so:"Solitary",lf:"3–4 years",f:"Born with fur and open eyes; rabbits are born blind and bald."},
{n:"Mouse",e:"🐭",c:"Mammal",d:"Omnivore",r:["Worldwide"],dg:"no",ac:"night",h:false,p:"common",dm:true,et:"no",cv:"Fur",co:["brown","grey","white"],sz:"tiny",lg:4,fl:false,sw:true,eg:false,so:"Groups",lf:"1–2 years",f:"Sings ultrasonic songs to attract mates, far above our hearing."},
{n:"Rat",e:"🐀",c:"Mammal",d:"Omnivore",r:["Worldwide"],dg:"no",ac:"night",h:false,p:"common",dm:true,et:"some",cv:"Fur",co:["brown","black","white"],sz:"small",lg:4,fl:false,sw:true,eg:false,so:"Groups",lf:"2–3 years",f:"Ticklish, and laughs ultrasonically when you tickle them."},
{n:"Hamster",e:"🐹",c:"Mammal",d:"Omnivore",r:["Asia","Europe"],dg:"no",ac:"night",h:true,p:"common",dm:true,et:"no",cv:"Fur",co:["gold","white","brown"],sz:"tiny",lg:4,fl:false,sw:true,eg:false,so:"Solitary",lf:"2–3 years",f:"Nearly every pet golden hamster descends from one 1930 litter."},
{n:"Guinea pig",e:"🐹",c:"Mammal",d:"Herbivore",r:["South America"],dg:"no",ac:"both",h:false,p:"common",dm:true,et:"yes",cv:"Fur",co:["brown","white","black","ginger"],sz:"small",lg:4,fl:false,sw:true,eg:false,so:"Groups",lf:"5–7 years",f:"Not a pig, and nothing to do with Guinea."},
{n:"Ferret",e:"🦡",c:"Mammal",d:"Carnivore",r:["Europe","Worldwide"],dg:"no",ac:"both",h:false,p:"common",dm:true,et:"no",cv:"Fur",co:["cream","brown","black"],sz:"small",lg:4,fl:false,sw:true,eg:false,so:"Groups",lf:"6–10 years",f:"Domesticated over 2,000 years ago to flush rabbits from burrows."},
{n:"Otter",e:"🦦",c:"Mammal",d:"Carnivore",r:["Worldwide"],dg:"no",ac:"both",h:false,p:"no",dm:false,et:"no",cv:"Fur",co:["brown"],sz:"medium",lg:4,fl:false,sw:true,eg:false,so:"Groups",lf:"10–15 years",f:"Holds hands while sleeping so the group does not drift apart."},
{n:"Badger",e:"🦡",c:"Mammal",d:"Omnivore",r:["Europe","Asia","North America"],dg:"some",ac:"night",h:false,p:"no",dm:false,et:"no",cv:"Fur",co:["black","white","grey"],sz:"medium",lg:4,fl:false,sw:true,eg:false,so:"Groups",lf:"8–14 years",f:"Setts get passed down and extended for a century or more."},
{n:"Raccoon",e:"🦝",c:"Mammal",d:"Omnivore",r:["North America"],dg:"some",ac:"night",h:false,p:"no",dm:false,et:"some",cv:"Fur",co:["grey","black"],sz:"medium",lg:4,fl:false,sw:true,eg:false,so:"Solitary",lf:"2–3 years",f:"Most of what it 'sees' with its hands comes through touch."},
{n:"Skunk",e:"🦨",c:"Mammal",d:"Omnivore",r:["North America"],dg:"no",ac:"night",h:false,p:"some",dm:false,et:"no",cv:"Fur",co:["black","white"],sz:"small",lg:4,fl:false,sw:true,eg:false,so:"Solitary",lf:"3–7 years",f:"Only about six sprays in the tank, and weeks to reload."},
{n:"Deer",e:"🦌",c:"Mammal",d:"Herbivore",r:["Worldwide"],dg:"some",ac:"both",h:false,p:"no",dm:false,et:"yes",cv:"Fur",co:["brown"],sz:"large",lg:4,fl:false,sw:true,eg:false,so:"Herds",lf:"10–20 years",f:"Antlers are bone, grown and shed every year — horns never are."},
{n:"Moose",a:["elk"],e:"🫎",c:"Mammal",d:"Herbivore",r:["North America","Europe"],dg:"some",ac:"both",h:false,p:"no",dm:false,et:"yes",cv:"Fur",co:["brown"],sz:"huge",lg:4,fl:false,sw:true,eg:false,so:"Solitary",lf:"15–25 years",f:"Dives several metres underwater to reach pondweed."},
{n:"Horse",e:"🐴",c:"Mammal",d:"Herbivore",r:["Worldwide"],dg:"some",ac:"day",h:false,p:"some",dm:true,et:"some",cv:"Fur",co:["brown","black","white","grey"],sz:"large",lg:4,fl:false,sw:true,eg:false,so:"Herds",lf:"25–30 years",f:"Sleeps standing up by locking its knees."},
{n:"Cow",a:["cattle","bull"],e:"🐮",c:"Mammal",d:"Herbivore",r:["Worldwide"],dg:"some",ac:"day",h:false,p:"no",dm:true,et:"yes",cv:"Fur",co:["black","white","brown"],sz:"large",lg:4,fl:false,sw:true,eg:false,so:"Herds",lf:"18–22 years",f:"Has best friends, and gets stressed when separated from them."},
{n:"Pig",e:"🐷",c:"Mammal",d:"Omnivore",r:["Worldwide"],dg:"some",ac:"day",h:false,p:"some",dm:true,et:"yes",cv:"Bristles",co:["pink","black","brown"],sz:"large",lg:4,fl:false,sw:true,eg:false,so:"Groups",lf:"15–20 years",f:"Cannot sweat, which is exactly why they use mud."},
{n:"Sheep",e:"🐑",c:"Mammal",d:"Herbivore",r:["Worldwide"],dg:"no",ac:"day",h:false,p:"no",dm:true,et:"yes",cv:"Wool",co:["white","black","brown"],sz:"medium",lg:4,fl:false,sw:true,eg:false,so:"Flocks",lf:"10–12 years",f:"Recognises and remembers about 50 individual faces for years."},
{n:"Goat",e:"🐐",c:"Mammal",d:"Herbivore",r:["Worldwide"],dg:"no",ac:"day",h:false,p:"some",dm:true,et:"yes",cv:"Fur",co:["white","brown","black"],sz:"medium",lg:4,fl:false,sw:true,eg:false,so:"Herds",lf:"15–18 years",f:"Rectangular pupils, giving it almost 320° of vision."},
{n:"Camel",e:"🐫",c:"Mammal",d:"Herbivore",r:["Africa","Asia"],dg:"some",ac:"day",h:false,p:"no",dm:true,et:"yes",cv:"Fur",co:["tan","brown"],sz:"large",lg:4,fl:false,sw:true,eg:false,so:"Herds",lf:"40–50 years",f:"The humps are fat, not water."},
{n:"Llama",e:"🦙",c:"Mammal",d:"Herbivore",r:["South America"],dg:"no",ac:"day",h:false,p:"some",dm:true,et:"yes",cv:"Wool",co:["white","brown","black"],sz:"large",lg:4,fl:false,sw:true,eg:false,so:"Herds",lf:"15–25 years",f:"Spits mostly at each other, rarely at you, and only when cross."},
{n:"Alpaca",e:"🦙",c:"Mammal",d:"Herbivore",r:["South America"],dg:"no",ac:"day",h:false,p:"some",dm:true,et:"yes",cv:"Wool",co:["white","brown","black","cream"],sz:"medium",lg:4,fl:false,sw:true,eg:false,so:"Herds",lf:"15–20 years",f:"Hums to itself constantly, and to its young."},
{n:"Bat",e:"🦇",c:"Mammal",d:"Insectivore",r:["Worldwide"],dg:"some",ac:"night",h:true,p:"no",dm:false,et:"some",cv:"Fur",co:["brown","black"],sz:"tiny",lg:2,fl:true,sw:false,eg:false,so:"Colonies",lf:"20–30 years",f:"The only mammal that genuinely flies rather than glides."},
{n:"Whale",a:["blue whale","humpback"],e:"🐳",c:"Mammal",d:"Carnivore",r:["Oceans"],dg:"no",ac:"both",h:false,p:"no",dm:false,et:"some",cv:"Skin",co:["grey","blue","black"],sz:"huge",lg:0,fl:false,sw:true,eg:false,so:"Pods",lf:"70–90 years",f:"A blue whale's heart is roughly the size of a small car."},
{n:"Dolphin",e:"🐬",c:"Mammal",d:"Carnivore",r:["Oceans"],dg:"no",ac:"both",h:false,p:"no",dm:false,et:"no",cv:"Skin",co:["grey"],sz:"large",lg:0,fl:false,sw:true,eg:false,so:"Pods",lf:"40–60 years",f:"Sleeps one half of the brain at a time, so it keeps breathing."},
{n:"Orca",a:["killer whale"],e:"🐋",c:"Mammal",d:"Carnivore",r:["Oceans"],dg:"some",ac:"both",h:false,p:"no",dm:false,et:"no",cv:"Skin",co:["black","white"],sz:"huge",lg:0,fl:false,sw:true,eg:false,so:"Pods",lf:"50–80 years",f:"Actually the largest dolphin, and pods have their own dialects."},
{n:"Seal",e:"🦭",c:"Mammal",d:"Carnivore",r:["Oceans","Arctic","Antarctic"],dg:"some",ac:"both",h:false,p:"no",dm:false,et:"some",cv:"Fur",co:["grey","brown"],sz:"large",lg:0,fl:false,sw:true,eg:false,so:"Colonies",lf:"25–30 years",f:"Can sleep underwater, surfacing to breathe without waking."},
{n:"Walrus",e:"🦭",c:"Mammal",d:"Carnivore",r:["Arctic"],dg:"some",ac:"both",h:false,p:"no",dm:false,et:"some",cv:"Skin",co:["brown"],sz:"huge",lg:0,fl:false,sw:true,eg:false,so:"Herds",lf:"30–40 years",f:"Uses its tusks like ice picks to haul itself out of the water."},
{n:"Hyena",e:"🐺",c:"Mammal",d:"Carnivore",r:["Africa","Asia"],dg:"yes",ac:"night",h:false,p:"no",dm:false,et:"no",cv:"Fur",co:["brown","spotted"],sz:"large",lg:4,fl:false,sw:true,eg:false,so:"Clans",lf:"12–25 years",f:"Clans are led by females, and the lowest female outranks every male."},
{n:"Meerkat",e:"🦫",c:"Mammal",d:"Insectivore",r:["Africa"],dg:"no",ac:"day",h:false,p:"no",dm:false,et:"no",cv:"Fur",co:["tan","brown"],sz:"small",lg:4,fl:false,sw:false,eg:false,so:"Mobs",lf:"12–14 years",f:"Takes turns on sentry duty while the rest of the mob eats."},
{n:"Bison",a:["buffalo"],e:"🦬",c:"Mammal",d:"Herbivore",r:["North America","Europe"],dg:"yes",ac:"day",h:false,p:"no",dm:false,et:"yes",cv:"Fur",co:["brown"],sz:"huge",lg:4,fl:false,sw:true,eg:false,so:"Herds",lf:"15–20 years",f:"Two tonnes that can still clear a six-foot fence."},
{n:"Anteater",e:"🐜",c:"Mammal",d:"Insectivore",r:["South America","Central America"],dg:"some",ac:"both",h:false,p:"no",dm:false,et:"no",cv:"Fur",co:["grey","black","white"],sz:"medium",lg:4,fl:false,sw:true,eg:false,so:"Solitary",lf:"14–16 years",f:"No teeth at all, and a tongue that flicks 150 times a minute."},
{n:"Armadillo",e:"🦫",c:"Mammal",d:"Insectivore",r:["South America","North America"],dg:"no",ac:"night",h:false,p:"no",dm:false,et:"some",cv:"Armour",co:["brown","grey"],sz:"small",lg:4,fl:false,sw:true,eg:false,so:"Solitary",lf:"12–15 years",f:"Nine-banded armadillos always give birth to identical quadruplets."},
{n:"Pangolin",e:"🦔",c:"Mammal",d:"Insectivore",r:["Africa","Asia"],dg:"no",ac:"night",h:false,p:"no",dm:false,et:"some",cv:"Scales",co:["brown"],sz:"medium",lg:4,fl:false,sw:true,eg:false,so:"Solitary",lf:"15–20 years",f:"The only mammal covered in scales, and the most trafficked."},
{n:"Porcupine",e:"🦔",c:"Mammal",d:"Herbivore",r:["Africa","Asia","North America"],dg:"some",ac:"night",h:false,p:"no",dm:false,et:"some",cv:"Quills",co:["black","white","brown"],sz:"medium",lg:4,fl:false,sw:true,eg:false,so:"Solitary",lf:"15–20 years",f:"Cannot shoot its quills — that part is a myth."},
{n:"Beaver",e:"🦫",c:"Mammal",d:"Herbivore",r:["North America","Europe"],dg:"no",ac:"night",h:false,p:"no",dm:false,et:"some",cv:"Fur",co:["brown"],sz:"medium",lg:4,fl:false,sw:true,eg:false,so:"Families",lf:"10–15 years",f:"Its teeth are orange because they are reinforced with iron."},
{n:"Mole",e:"🦡",c:"Mammal",d:"Insectivore",r:["Europe","Asia","North America"],dg:"no",ac:"both",h:false,p:"no",dm:false,et:"no",cv:"Fur",co:["black","grey"],sz:"tiny",lg:4,fl:false,sw:true,eg:false,so:"Solitary",lf:"3–6 years",f:"Stores live earthworms, paralysed, in an underground larder."},

{n:"Chicken",a:["hen","rooster"],e:"🐔",c:"Bird",d:"Omnivore",r:["Worldwide"],dg:"no",ac:"day",h:false,p:"some",dm:true,et:"yes",cv:"Feathers",co:["white","brown","black"],sz:"small",lg:2,fl:false,sw:false,eg:true,so:"Flocks",lf:"5–10 years",f:"There are more of them alive than any other bird, by miles."},
{n:"Duck",e:"🦆",c:"Bird",d:"Omnivore",r:["Worldwide"],dg:"no",ac:"day",h:false,p:"some",dm:true,et:"yes",cv:"Feathers",co:["brown","green","white"],sz:"small",lg:2,fl:true,sw:true,eg:true,so:"Flocks",lf:"5–10 years",f:"Ducklings imprint on the first moving thing they see."},
{n:"Goose",e:"🪿",c:"Bird",d:"Herbivore",r:["Worldwide"],dg:"some",ac:"day",h:false,p:"no",dm:true,et:"yes",cv:"Feathers",co:["grey","white","black"],sz:"medium",lg:2,fl:true,sw:true,eg:true,so:"Flocks",lf:"10–24 years",f:"Genuinely will chase you, and remembers faces."},
{n:"Swan",e:"🦢",c:"Bird",d:"Herbivore",r:["Europe","Asia","North America"],dg:"some",ac:"day",h:false,p:"no",dm:false,et:"no",cv:"Feathers",co:["white","black"],sz:"large",lg:2,fl:true,sw:true,eg:true,so:"Pairs",lf:"20–30 years",f:"Mates for life, and in the UK the Crown owns the wild ones."},
{n:"Penguin",e:"🐧",c:"Bird",d:"Carnivore",r:["Antarctic","Africa","South America"],dg:"no",ac:"day",h:false,p:"no",dm:false,et:"no",cv:"Feathers",co:["black","white"],sz:"medium",lg:2,fl:false,sw:true,eg:true,so:"Colonies",lf:"15–20 years",f:"Some species propose with a carefully chosen pebble."},
{n:"Owl",e:"🦉",c:"Bird",d:"Carnivore",r:["Worldwide"],dg:"no",ac:"night",h:false,p:"no",dm:false,et:"no",cv:"Feathers",co:["brown","white","grey"],sz:"medium",lg:2,fl:true,sw:false,eg:true,so:"Solitary",lf:"10–25 years",f:"Cannot move its eyes, so it turns its head 270° instead."},
{n:"Eagle",e:"🦅",c:"Bird",d:"Carnivore",r:["Worldwide"],dg:"some",ac:"day",h:false,p:"no",dm:false,et:"no",cv:"Feathers",co:["brown","white"],sz:"large",lg:2,fl:true,sw:false,eg:true,so:"Pairs",lf:"20–30 years",f:"Spots a rabbit from about two miles up."},
{n:"Parrot",e:"🦜",c:"Bird",d:"Herbivore",r:["South America","Africa","Australia"],dg:"no",ac:"day",h:false,p:"common",dm:false,et:"no",cv:"Feathers",co:["green","red","blue","yellow"],sz:"medium",lg:2,fl:true,sw:false,eg:true,so:"Flocks",lf:"50–80 years",f:"Some outlive their owners, and get written into wills."},
{n:"Peacock",a:["peafowl"],e:"🦚",c:"Bird",d:"Omnivore",r:["Asia"],dg:"no",ac:"day",h:false,p:"some",dm:false,et:"some",cv:"Feathers",co:["blue","green"],sz:"large",lg:2,fl:true,sw:false,eg:true,so:"Groups",lf:"15–20 years",f:"The colour is structural — the feathers contain no blue pigment."},
{n:"Flamingo",e:"🦩",c:"Bird",d:"Omnivore",r:["Africa","South America","Europe"],dg:"no",ac:"day",h:false,p:"no",dm:false,et:"no",cv:"Feathers",co:["pink"],sz:"large",lg:2,fl:true,sw:true,eg:true,so:"Flocks",lf:"20–30 years",f:"Born grey. The pink comes entirely from what they eat."},
{n:"Ostrich",e:"🦤",c:"Bird",d:"Omnivore",r:["Africa"],dg:"some",ac:"day",h:false,p:"no",dm:false,et:"yes",cv:"Feathers",co:["black","white","brown"],sz:"huge",lg:2,fl:false,sw:true,eg:true,so:"Groups",lf:"40–45 years",f:"Its eye is bigger than its brain."},
{n:"Pigeon",a:["dove"],e:"🐦",c:"Bird",d:"Herbivore",r:["Worldwide"],dg:"no",ac:"day",h:false,p:"some",dm:true,et:"some",cv:"Feathers",co:["grey","white"],sz:"small",lg:2,fl:true,sw:false,eg:true,so:"Flocks",lf:"3–6 years",f:"Passes the mirror test — one of very few non-mammals that do."},
{n:"Crow",a:["raven"],e:"🐦‍⬛",c:"Bird",d:"Omnivore",r:["Worldwide"],dg:"no",ac:"day",h:false,p:"no",dm:false,et:"no",cv:"Feathers",co:["black"],sz:"medium",lg:2,fl:true,sw:false,eg:true,so:"Groups",lf:"7–15 years",f:"Remembers a face that wronged it, and tells the other crows."},
{n:"Robin",e:"🐦",c:"Bird",d:"Omnivore",r:["Europe","North America"],dg:"no",ac:"day",h:false,p:"no",dm:false,et:"no",cv:"Feathers",co:["brown","red"],sz:"tiny",lg:2,fl:true,sw:false,eg:true,so:"Solitary",lf:"2 years",f:"Fiercely territorial — that friendly garden bird will fight to the death."},
{n:"Hummingbird",e:"🐦",c:"Bird",d:"Herbivore",r:["North America","South America"],dg:"no",ac:"day",h:false,p:"no",dm:false,et:"no",cv:"Feathers",co:["green","red","blue"],sz:"tiny",lg:2,fl:true,sw:false,eg:true,so:"Solitary",lf:"3–5 years",f:"The only bird that can fly backwards."},
{n:"Woodpecker",e:"🐦",c:"Bird",d:"Insectivore",r:["Worldwide"],dg:"no",ac:"day",h:false,p:"no",dm:false,et:"no",cv:"Feathers",co:["black","white","red"],sz:"small",lg:2,fl:true,sw:false,eg:true,so:"Solitary",lf:"4–12 years",f:"Its tongue wraps around the back of its skull as a shock absorber."},
{n:"Seagull",a:["gull"],w:"Gull",e:"🐦",c:"Bird",d:"Omnivore",r:["Worldwide"],dg:"no",ac:"day",h:false,p:"no",dm:false,et:"no",cv:"Feathers",co:["white","grey"],sz:"medium",lg:2,fl:true,sw:true,eg:true,so:"Flocks",lf:"10–15 years",f:"Drums its feet on grass to imitate rain and fool the worms up."},
{n:"Turkey",e:"🦃",c:"Bird",d:"Omnivore",r:["North America"],dg:"no",ac:"day",h:false,p:"no",dm:true,et:"yes",cv:"Feathers",co:["brown","black"],sz:"large",lg:2,fl:true,sw:false,eg:true,so:"Flocks",lf:"3–5 years",f:"Wild ones fly perfectly well, at up to 55 mph."},

{n:"Crocodile",e:"🐊",c:"Reptile",d:"Carnivore",r:["Africa","Asia","Australia","Americas"],dg:"yes",ac:"night",h:false,p:"no",dm:false,et:"some",cv:"Scales",co:["green","brown"],sz:"huge",lg:4,fl:false,sw:true,eg:true,so:"Solitary",lf:"70–100 years",f:"Strongest bite ever measured on a living animal."},
{n:"Alligator",e:"🐊",c:"Reptile",d:"Carnivore",r:["North America","Asia"],dg:"yes",ac:"night",h:false,p:"no",dm:false,et:"some",cv:"Scales",co:["black","grey"],sz:"huge",lg:4,fl:false,sw:true,eg:true,so:"Solitary",lf:"35–50 years",f:"Wide rounded snout; a crocodile's is narrow and shows teeth."},
{n:"Snake",a:["python","cobra","viper"],e:"🐍",c:"Reptile",d:"Carnivore",r:["Worldwide"],dg:"yes",ac:"both",h:true,p:"some",dm:false,et:"some",cv:"Scales",co:["green","brown","black","yellow"],sz:"medium",lg:0,fl:false,sw:true,eg:true,so:"Solitary",lf:"10–30 years",f:"Smells with its tongue, delivering scent to the roof of its mouth."},
{n:"Lizard",e:"🦎",c:"Reptile",d:"Insectivore",r:["Worldwide"],dg:"no",ac:"day",h:false,p:"common",dm:false,et:"some",cv:"Scales",co:["green","brown","grey"],sz:"small",lg:4,fl:false,sw:true,eg:true,so:"Solitary",lf:"5–15 years",f:"Many can drop their tail and grow a new one."},
{n:"Chameleon",e:"🦎",c:"Reptile",d:"Insectivore",r:["Africa","Asia"],dg:"no",ac:"day",h:false,p:"some",dm:false,et:"no",cv:"Scales",co:["green","brown","blue"],sz:"small",lg:4,fl:false,sw:false,eg:true,so:"Solitary",lf:"5–10 years",f:"Changes colour for mood and temperature, not to match wallpaper."},
{n:"Komodo dragon",e:"🦎",c:"Reptile",d:"Carnivore",r:["Asia"],dg:"yes",ac:"day",h:false,p:"no",dm:false,et:"no",cv:"Scales",co:["grey","brown"],sz:"large",lg:4,fl:false,sw:true,eg:true,so:"Solitary",lf:"30 years",f:"The largest lizard alive, and it is genuinely venomous."},
{n:"Tortoise",e:"🐢",c:"Reptile",d:"Herbivore",r:["Worldwide"],dg:"no",ac:"day",h:true,p:"some",dm:false,et:"some",cv:"Shell",co:["brown","grey"],sz:"medium",lg:4,fl:false,sw:false,eg:true,so:"Solitary",lf:"80–150 years",f:"Routinely outlives the person who bought it."},
{n:"Turtle",e:"🐢",c:"Reptile",d:"Omnivore",r:["Oceans","Worldwide"],dg:"no",ac:"day",h:false,p:"some",dm:false,et:"some",cv:"Shell",co:["green","brown"],sz:"large",lg:4,fl:false,sw:true,eg:true,so:"Solitary",lf:"50–100 years",f:"Females return to the exact beach where they hatched."},
{n:"Iguana",e:"🦎",c:"Reptile",d:"Herbivore",r:["South America","Central America"],dg:"no",ac:"day",h:false,p:"some",dm:false,et:"some",cv:"Scales",co:["green","orange"],sz:"medium",lg:4,fl:false,sw:true,eg:true,so:"Solitary",lf:"15–20 years",f:"Has a light-sensing 'third eye' on top of its head."},
{n:"Gecko",e:"🦎",c:"Reptile",d:"Insectivore",r:["Worldwide"],dg:"no",ac:"night",h:false,p:"common",dm:false,et:"no",cv:"Scales",co:["brown","yellow","grey"],sz:"tiny",lg:4,fl:false,sw:false,eg:true,so:"Solitary",lf:"10–20 years",f:"Sticks to glass using molecular forces, not suction or glue."},

{n:"Frog",e:"🐸",c:"Amphibian",d:"Insectivore",r:["Worldwide"],dg:"some",ac:"night",h:true,p:"some",dm:false,et:"yes",cv:"Skin",co:["green","brown"],sz:"tiny",lg:4,fl:false,sw:true,eg:true,so:"Groups",lf:"4–15 years",f:"Drinks through its skin — it never takes a sip."},
{n:"Toad",e:"🐸",c:"Amphibian",d:"Insectivore",r:["Worldwide"],dg:"some",ac:"night",h:true,p:"some",dm:false,et:"no",cv:"Skin",co:["brown","green"],sz:"small",lg:4,fl:false,sw:true,eg:true,so:"Solitary",lf:"10–12 years",f:"Dry warty skin and it walks; frogs are wet and they jump."},
{n:"Axolotl",e:"🦎",c:"Amphibian",d:"Carnivore",r:["North America"],dg:"no",ac:"both",h:false,p:"common",dm:false,et:"no",cv:"Skin",co:["pink","white","brown"],sz:"small",lg:4,fl:false,sw:true,eg:true,so:"Solitary",lf:"10–15 years",f:"Regrows legs, tail, and parts of its own brain."},
{n:"Salamander",e:"🦎",c:"Amphibian",d:"Insectivore",r:["Worldwide"],dg:"some",ac:"night",h:true,p:"some",dm:false,et:"no",cv:"Skin",co:["black","yellow","orange"],sz:"small",lg:4,fl:false,sw:true,eg:true,so:"Solitary",lf:"10–20 years",f:"Some breathe entirely through their skin, having no lungs at all."},
{n:"Newt",e:"🦎",c:"Amphibian",d:"Insectivore",r:["Europe","Asia","North America"],dg:"some",ac:"night",h:true,p:"some",dm:false,et:"no",cv:"Skin",co:["brown","orange"],sz:"tiny",lg:4,fl:false,sw:true,eg:true,so:"Solitary",lf:"6–14 years",f:"Protected by law in the UK, to the eternal grief of builders."},

{n:"Shark",a:["great white"],e:"🦈",c:"Fish",d:"Carnivore",r:["Oceans"],dg:"yes",ac:"both",h:false,p:"no",dm:false,et:"some",cv:"Skin",co:["grey","blue"],sz:"huge",lg:0,fl:false,sw:true,eg:true,so:"Solitary",lf:"20–70 years",f:"Older than trees. They predate Saturn's rings, too."},
{n:"Goldfish",e:"🐠",c:"Fish",d:"Omnivore",r:["Worldwide"],dg:"no",ac:"day",h:false,p:"common",dm:true,et:"no",cv:"Scales",co:["orange","white"],sz:"tiny",lg:0,fl:false,sw:true,eg:true,so:"Groups",lf:"10–25 years",f:"The three-second memory is a myth — it is more like months."},
{n:"Clownfish",e:"🐠",c:"Fish",d:"Omnivore",r:["Oceans"],dg:"no",ac:"day",h:false,p:"common",dm:false,et:"no",cv:"Scales",co:["orange","white","black"],sz:"tiny",lg:0,fl:false,sw:true,eg:true,so:"Groups",lf:"6–10 years",f:"All are born male, and the dominant one becomes female."},
{n:"Salmon",e:"🐟",c:"Fish",d:"Carnivore",r:["Oceans","Rivers"],dg:"no",ac:"day",h:false,p:"no",dm:true,et:"yes",cv:"Scales",co:["silver","pink"],sz:"medium",lg:0,fl:false,sw:true,eg:true,so:"Groups",lf:"3–8 years",f:"Navigates back to its home river by smell alone."},
{n:"Pufferfish",e:"🐡",c:"Fish",d:"Omnivore",r:["Oceans"],dg:"yes",ac:"day",h:false,p:"some",dm:false,et:"some",cv:"Skin",co:["brown","yellow"],sz:"small",lg:0,fl:false,sw:true,eg:true,so:"Solitary",lf:"10 years",f:"Contains a poison over a thousand times deadlier than cyanide."},
{n:"Seahorse",e:"🐠",c:"Fish",d:"Carnivore",r:["Oceans"],dg:"no",ac:"day",h:false,p:"some",dm:false,et:"some",cv:"Skin",co:["yellow","brown","orange"],sz:"tiny",lg:0,fl:false,sw:true,eg:true,so:"Pairs",lf:"1–5 years",f:"The male gets pregnant and gives birth."},
{n:"Eel",e:"🐍",c:"Fish",d:"Carnivore",r:["Oceans","Rivers"],dg:"some",ac:"night",h:false,p:"no",dm:false,et:"yes",cv:"Skin",co:["brown","green"],sz:"medium",lg:0,fl:false,sw:true,eg:true,so:"Solitary",lf:"15–85 years",f:"Nobody has ever seen European eels breed. Still a mystery."},

{n:"Octopus",e:"🐙",c:"Mollusc",d:"Carnivore",r:["Oceans"],dg:"some",ac:"night",h:false,p:"some",dm:false,et:"yes",cv:"Skin",co:["red","brown","grey"],sz:"medium",lg:8,fl:false,sw:true,eg:true,so:"Solitary",lf:"1–3 years",f:"Three hearts, blue blood, and two thirds of its neurons in its arms."},
{n:"Squid",e:"🦑",c:"Mollusc",d:"Carnivore",r:["Oceans"],dg:"some",ac:"night",h:false,p:"no",dm:false,et:"yes",cv:"Skin",co:["red","white"],sz:"medium",lg:10,fl:false,sw:true,eg:true,so:"Groups",lf:"1–5 years",f:"The giant squid has the largest eye of any animal — dinner-plate sized."},
{n:"Snail",e:"🐌",c:"Mollusc",d:"Herbivore",r:["Worldwide"],dg:"no",ac:"night",h:true,p:"some",dm:false,et:"yes",cv:"Shell",co:["brown","grey"],sz:"tiny",lg:0,fl:false,sw:false,eg:true,so:"Solitary",lf:"2–7 years",f:"Has thousands of microscopic teeth on a ribbon-like tongue."},
{n:"Jellyfish",e:"🪼",c:"Cnidarian",d:"Carnivore",r:["Oceans"],dg:"yes",ac:"both",h:false,p:"some",dm:false,et:"some",cv:"None",co:["clear","blue","pink"],sz:"medium",lg:0,fl:false,sw:true,eg:true,so:"Blooms",lf:"1 year",f:"No brain, no heart, no blood, and older than the dinosaurs."},
{n:"Crab",e:"🦀",c:"Crustacean",d:"Omnivore",r:["Oceans","Worldwide"],dg:"no",ac:"both",h:false,p:"some",dm:false,et:"yes",cv:"Shell",co:["red","brown","orange"],sz:"small",lg:10,fl:false,sw:true,eg:true,so:"Groups",lf:"3–30 years",f:"Evolution keeps independently reinventing the crab shape."},
{n:"Lobster",e:"🦞",c:"Crustacean",d:"Omnivore",r:["Oceans"],dg:"no",ac:"night",h:false,p:"no",dm:false,et:"yes",cv:"Shell",co:["red","blue","brown"],sz:"medium",lg:10,fl:false,sw:true,eg:true,so:"Solitary",lf:"50–100 years",f:"Does not really weaken with age — it just keeps growing."},
{n:"Shrimp",a:["prawn"],e:"🦐",c:"Crustacean",d:"Omnivore",r:["Oceans"],dg:"no",ac:"night",h:false,p:"some",dm:true,et:"yes",cv:"Shell",co:["pink","grey"],sz:"tiny",lg:10,fl:false,sw:true,eg:true,so:"Groups",lf:"1–6 years",f:"The pistol shrimp's claw snaps loud enough to stun a fish."},

{n:"Spider",a:["tarantula"],e:"🕷️",c:"Arachnid",d:"Carnivore",r:["Worldwide"],dg:"some",ac:"night",h:false,p:"some",dm:false,et:"some",cv:"Exoskeleton",co:["black","brown"],sz:"tiny",lg:8,fl:false,sw:false,eg:true,so:"Solitary",lf:"1–20 years",f:"Silk is, weight for weight, stronger than steel."},
{n:"Scorpion",e:"🦂",c:"Arachnid",d:"Carnivore",r:["Africa","Asia","Americas","Australia"],dg:"yes",ac:"night",h:false,p:"some",dm:false,et:"some",cv:"Exoskeleton",co:["black","brown","yellow"],sz:"tiny",lg:8,fl:false,sw:false,eg:false,so:"Solitary",lf:"3–8 years",f:"Glows bright blue-green under ultraviolet light."},
{n:"Bee",e:"🐝",c:"Insect",d:"Herbivore",r:["Worldwide"],dg:"some",ac:"day",h:false,p:"some",dm:true,et:"no",cv:"Exoskeleton",co:["yellow","black"],sz:"tiny",lg:6,fl:true,sw:false,eg:true,so:"Colonies",lf:"6 weeks",f:"Tells the hive where flowers are by dancing the direction."},
{n:"Wasp",e:"🐝",c:"Insect",d:"Omnivore",r:["Worldwide"],dg:"some",ac:"day",h:true,p:"no",dm:false,et:"no",cv:"Exoskeleton",co:["yellow","black"],sz:"tiny",lg:6,fl:true,sw:false,eg:true,so:"Colonies",lf:"1 year",f:"Invented paper long before we did, by chewing wood."},
{n:"Ant",e:"🐜",c:"Insect",d:"Omnivore",r:["Worldwide"],dg:"no",ac:"both",h:false,p:"some",dm:false,et:"some",cv:"Exoskeleton",co:["black","red"],sz:"tiny",lg:6,fl:false,sw:false,eg:true,so:"Colonies",lf:"1–15 years",f:"All the ants on Earth weigh roughly as much as all the people."},
{n:"Butterfly",e:"🦋",c:"Insect",d:"Herbivore",r:["Worldwide"],dg:"no",ac:"day",h:false,p:"no",dm:false,et:"no",cv:"Scales",co:["orange","blue","black","white"],sz:"tiny",lg:6,fl:true,sw:false,eg:true,so:"Solitary",lf:"2–11 months",f:"Tastes with its feet."},
{n:"Moth",e:"🦋",c:"Insect",d:"Herbivore",r:["Worldwide"],dg:"no",ac:"night",h:false,p:"no",dm:false,et:"some",cv:"Scales",co:["brown","grey","white"],sz:"tiny",lg:6,fl:true,sw:false,eg:true,so:"Solitary",lf:"1–6 months",f:"Not attracted to light so much as confused by it."},
{n:"Ladybird",a:["ladybug"],e:"🐞",c:"Insect",d:"Carnivore",r:["Worldwide"],dg:"no",ac:"day",h:true,p:"no",dm:false,et:"no",cv:"Exoskeleton",co:["red","black"],sz:"tiny",lg:6,fl:true,sw:false,eg:true,so:"Groups",lf:"1 year",f:"Eats about 5,000 aphids in a lifetime, which is why gardeners love it."},
{n:"Dragonfly",e:"🪰",c:"Insect",d:"Carnivore",r:["Worldwide"],dg:"no",ac:"day",h:false,p:"no",dm:false,et:"no",cv:"Exoskeleton",co:["blue","green"],sz:"tiny",lg:6,fl:true,sw:false,eg:true,so:"Solitary",lf:"6 months",f:"Catches about 95% of what it chases — the best hunter going."},
{n:"Grasshopper",a:["cricket","locust"],e:"🦗",c:"Insect",d:"Herbivore",r:["Worldwide"],dg:"no",ac:"day",h:false,p:"some",dm:false,et:"yes",cv:"Exoskeleton",co:["green","brown"],sz:"tiny",lg:6,fl:true,sw:false,eg:true,so:"Groups",lf:"1 year",f:"Its ears are on its abdomen, not its head."},
{n:"Beetle",e:"🪲",c:"Insect",d:"Omnivore",r:["Worldwide"],dg:"no",ac:"both",h:true,p:"some",dm:false,et:"some",cv:"Exoskeleton",co:["black","brown","green"],sz:"tiny",lg:6,fl:true,sw:false,eg:true,so:"Solitary",lf:"1–3 years",f:"One in every four known animal species is a beetle."},
{n:"Fly",a:["housefly"],e:"🪰",c:"Insect",d:"Omnivore",r:["Worldwide"],dg:"no",ac:"day",h:false,p:"no",dm:false,et:"no",cv:"Exoskeleton",co:["black","grey"],sz:"tiny",lg:6,fl:true,sw:false,eg:true,so:"Groups",lf:"1 month",f:"Sees time more slowly than you, which is why you keep missing."},
{n:"Mosquito",e:"🦟",c:"Insect",d:"Omnivore",r:["Worldwide"],dg:"yes",ac:"night",h:false,p:"no",dm:false,et:"no",cv:"Exoskeleton",co:["black","brown"],sz:"tiny",lg:6,fl:true,sw:false,eg:true,so:"Groups",lf:"2 months",f:"Kills more people every year than every other animal combined."},
{n:"Praying mantis",e:"🦗",c:"Insect",d:"Carnivore",r:["Worldwide"],dg:"no",ac:"day",h:false,p:"some",dm:false,et:"no",cv:"Exoskeleton",co:["green","brown"],sz:"tiny",lg:6,fl:true,sw:false,eg:true,so:"Solitary",lf:"1 year",f:"The only insect that can turn its head to look behind it."},
{n:"Worm",a:["earthworm"],w:"Earthworm",e:"🪱",c:"Annelid",d:"Omnivore",r:["Worldwide"],dg:"no",ac:"night",h:false,p:"no",dm:false,et:"some",cv:"Skin",co:["pink","brown"],sz:"tiny",lg:0,fl:false,sw:false,eg:true,so:"Solitary",lf:"1–8 years",f:"Five hearts, no eyes, and it breathes through its skin."},
];

if (typeof module !== 'undefined') module.exports = { ANIMALS };
